import type { SVGProps } from 'react';
type IconProps = SVGProps<SVGSVGElement>;
export declare const IconDiagram: (props: IconProps) => import("react").JSX.Element;
export declare const IconSidebar: (props: IconProps) => import("react").JSX.Element;
export declare const IconSearch: (props: IconProps) => import("react").JSX.Element;
export declare const IconPlus: (props: IconProps) => import("react").JSX.Element;
export declare const IconMinus: (props: IconProps) => import("react").JSX.Element;
export declare const IconFit: (props: IconProps) => import("react").JSX.Element;
export declare const IconCode: (props: IconProps) => import("react").JSX.Element;
export declare const IconDownload: (props: IconProps) => import("react").JSX.Element;
export declare const IconUpload: (props: IconProps) => import("react").JSX.Element;
export declare const IconSun: (props: IconProps) => import("react").JSX.Element;
export declare const IconMoon: (props: IconProps) => import("react").JSX.Element;
export declare const IconX: (props: IconProps) => import("react").JSX.Element;
export declare const IconEye: (props: IconProps) => import("react").JSX.Element;
export declare const IconEyeOff: (props: IconProps) => import("react").JSX.Element;
export declare const IconChevron: (props: IconProps) => import("react").JSX.Element;
export declare const IconLayout: (props: IconProps) => import("react").JSX.Element;
export declare const IconRefresh: (props: IconProps) => import("react").JSX.Element;
export declare const IconFocus: (props: IconProps) => import("react").JSX.Element;
export declare const IconCopy: (props: IconProps) => import("react").JSX.Element;
export declare const IconDatabase: (props: IconProps) => import("react").JSX.Element;
export declare const IconArrowRight: (props: IconProps) => import("react").JSX.Element;
export {};
